global:
  resolve_timeout: 5m

route:
  receiver: "frontend-alerts"

receivers:
  - name: "frontend-alerts"
    webhook_configs:
      - url: "http://host.docker.internal:5000/alerts"
        send_resolved: true