{
 "title": "revature2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wind Speed Forecast",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forecast_wind_speed{city=\"Mumbai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Forecast",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forecast_temperature{city=\"Mumbai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Forecast",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forecast_humidity{city=\"Mumbai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather_temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_temperature\r\n", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "Wind_speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_wind_speed{city=~\".*\"}\r\n",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_humidity{city=~\".*\"}\r\n",
     "legendFormat": "{{city}}"
    }
   ]
  }
 ]
}